name: Deploy

on:
  push:
    branches:
      - prod/v*
      - main

permissions: {}

defaults:
  run:
    shell: bash

env:
  AWS_REGION: ap-northeast-1

jobs:
  deploy:
    name: deploy-for-${{ github.ref_name }}
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get npm cache directory
        id: npm-cache-dir
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      - name: Get variables
        id: get_vars
        run: |
          if [ "${{ github.ref_name }}" = "main" ]
          then
            echo "STAGE=preview" >> "$GITHUB_OUTPUT"
            echo "VERSION=v0" >> "$GITHUB_OUTPUT"
          else
            echo "STAGE=`echo ${{ github.ref_name }} | cut -d'/' -f1`" >> "$GITHUB_OUTPUT"
            echo "VERSION=`echo ${{ github.ref_name }} | cut -d'/' -f2`" >> "$GITHUB_OUTPUT"
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          npm update -g npm
          npm install

      - name: Deploy for ${{ github.ref_name }}
        run: |
          npx cdk deploy --all --ci --require-approval never --concurrency 100 -c stage=${{ steps.get_vars.outputs.STAGE }} -c version=${{ steps.get_vars.outputs.VERSION }}
